#ifndef __MOTOR_MANAGER_CONFIG_H
#define __MOTOR_MANAGER_CONFIG_H

#define MOTOR_MANAGER_USE_CLI

#define ODRIVE_USE_MANAGER
#define DM_MOTOR_USE_MANAGER
#define GM_MOTOR_USE_MANAGER
#define STEADYWIN_CAN_USE_MANAGER
#define BRUSHESC775_USE_MANAGER

#define C610_USE_MANAGER
#define C620_USE_MANAGER
#define GM6020_USE_MANAGER

#endif